get:
	fvm flutter pub get

clean:
	fvm flutter clean

cleanGet:
	make clean
	make get

watch:
	fvm dart run build_runner watch --delete-conflicting-outputs

makeFeature:
	mason make feature

releaseApk:
	fvm flutter build apk --release

releaseAab:
	fvm flutter build appbundle --release
